importScripts("../Library/SW/SW.js");

cacheManager({
	name:"Statistic",
	build:[2019,12,23],
	list:[
		"Statistic.html",
		"resources/style.css",
		"resources/color.css",
		"resources/font.css",
		"resources/html.css",
		"resources/svg.css",
		"resources/header.js",
		"resources/core.js",
		"resources/status.js",
		"resources/menu.js",
		"resources/calc.js",
		"resources/input.js",
		"resources/html.js",
		"resources/svg.js",
		"resources/canvas.js",
		"resources/icon.png",
		"resources/favicon.ico",
		"resources/apple-touch-icon.png",
		"resources/tileImage.png",
		"manifest.json"
	]
});